/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedesSociaisRouteImport } from './routes/redes-sociais'
import { Route as PortalMedicoRouteImport } from './routes/portal-medico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesWhatsappRouteImport } from './routes/configuracoes-whatsapp'
import { Route as ConfiguracoesPacientesRouteImport } from './routes/configuracoes-pacientes'
import { Route as ConfiguracoesMedicosRouteImport } from './routes/configuracoes-medicos'
import { Route as ConfiguracoesDadosClinicaRouteImport } from './routes/configuracoes-dados-clinica'
import { Route as ConfiguracoesBaseConhecimentoRouteImport } from './routes/configuracoes-base-conhecimento'
import { Route as ConfiguracoesAgendaRouteImport } from './routes/configuracoes-agenda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const RedesSociaisRoute = RedesSociaisRouteImport.update({
  id: '/redes-sociais',
  path: '/redes-sociais',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalMedicoRoute = PortalMedicoRouteImport.update({
  id: '/portal-medico',
  path: '/portal-medico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesWhatsappRoute = ConfiguracoesWhatsappRouteImport.update({
  id: '/configuracoes-whatsapp',
  path: '/configuracoes-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPacientesRoute = ConfiguracoesPacientesRouteImport.update({
  id: '/configuracoes-pacientes',
  path: '/configuracoes-pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesMedicosRoute = ConfiguracoesMedicosRouteImport.update({
  id: '/configuracoes-medicos',
  path: '/configuracoes-medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesDadosClinicaRoute =
  ConfiguracoesDadosClinicaRouteImport.update({
    id: '/configuracoes-dados-clinica',
    path: '/configuracoes-dados-clinica',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesBaseConhecimentoRoute =
  ConfiguracoesBaseConhecimentoRouteImport.update({
    id: '/configuracoes-base-conhecimento',
    path: '/configuracoes-base-conhecimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesAgendaRoute = ConfiguracoesAgendaRouteImport.update({
  id: '/configuracoes-agenda',
  path: '/configuracoes-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/configuracoes-agenda': typeof ConfiguracoesAgendaRoute
  '/configuracoes-base-conhecimento': typeof ConfiguracoesBaseConhecimentoRoute
  '/configuracoes-dados-clinica': typeof ConfiguracoesDadosClinicaRoute
  '/configuracoes-medicos': typeof ConfiguracoesMedicosRoute
  '/configuracoes-pacientes': typeof ConfiguracoesPacientesRoute
  '/configuracoes-whatsapp': typeof ConfiguracoesWhatsappRoute
  '/login': typeof LoginRoute
  '/portal-medico': typeof PortalMedicoRoute
  '/redes-sociais': typeof RedesSociaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/configuracoes-agenda': typeof ConfiguracoesAgendaRoute
  '/configuracoes-base-conhecimento': typeof ConfiguracoesBaseConhecimentoRoute
  '/configuracoes-dados-clinica': typeof ConfiguracoesDadosClinicaRoute
  '/configuracoes-medicos': typeof ConfiguracoesMedicosRoute
  '/configuracoes-pacientes': typeof ConfiguracoesPacientesRoute
  '/configuracoes-whatsapp': typeof ConfiguracoesWhatsappRoute
  '/login': typeof LoginRoute
  '/portal-medico': typeof PortalMedicoRoute
  '/redes-sociais': typeof RedesSociaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/configuracoes-agenda': typeof ConfiguracoesAgendaRoute
  '/configuracoes-base-conhecimento': typeof ConfiguracoesBaseConhecimentoRoute
  '/configuracoes-dados-clinica': typeof ConfiguracoesDadosClinicaRoute
  '/configuracoes-medicos': typeof ConfiguracoesMedicosRoute
  '/configuracoes-pacientes': typeof ConfiguracoesPacientesRoute
  '/configuracoes-whatsapp': typeof ConfiguracoesWhatsappRoute
  '/login': typeof LoginRoute
  '/portal-medico': typeof PortalMedicoRoute
  '/redes-sociais': typeof RedesSociaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/atendimento'
    | '/configuracoes'
    | '/configuracoes-agenda'
    | '/configuracoes-base-conhecimento'
    | '/configuracoes-dados-clinica'
    | '/configuracoes-medicos'
    | '/configuracoes-pacientes'
    | '/configuracoes-whatsapp'
    | '/login'
    | '/portal-medico'
    | '/redes-sociais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/atendimento'
    | '/configuracoes'
    | '/configuracoes-agenda'
    | '/configuracoes-base-conhecimento'
    | '/configuracoes-dados-clinica'
    | '/configuracoes-medicos'
    | '/configuracoes-pacientes'
    | '/configuracoes-whatsapp'
    | '/login'
    | '/portal-medico'
    | '/redes-sociais'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/atendimento'
    | '/configuracoes'
    | '/configuracoes-agenda'
    | '/configuracoes-base-conhecimento'
    | '/configuracoes-dados-clinica'
    | '/configuracoes-medicos'
    | '/configuracoes-pacientes'
    | '/configuracoes-whatsapp'
    | '/login'
    | '/portal-medico'
    | '/redes-sociais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConfiguracoesAgendaRoute: typeof ConfiguracoesAgendaRoute
  ConfiguracoesBaseConhecimentoRoute: typeof ConfiguracoesBaseConhecimentoRoute
  ConfiguracoesDadosClinicaRoute: typeof ConfiguracoesDadosClinicaRoute
  ConfiguracoesMedicosRoute: typeof ConfiguracoesMedicosRoute
  ConfiguracoesPacientesRoute: typeof ConfiguracoesPacientesRoute
  ConfiguracoesWhatsappRoute: typeof ConfiguracoesWhatsappRoute
  LoginRoute: typeof LoginRoute
  PortalMedicoRoute: typeof PortalMedicoRoute
  RedesSociaisRoute: typeof RedesSociaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redes-sociais': {
      id: '/redes-sociais'
      path: '/redes-sociais'
      fullPath: '/redes-sociais'
      preLoaderRoute: typeof RedesSociaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-medico': {
      id: '/portal-medico'
      path: '/portal-medico'
      fullPath: '/portal-medico'
      preLoaderRoute: typeof PortalMedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-whatsapp': {
      id: '/configuracoes-whatsapp'
      path: '/configuracoes-whatsapp'
      fullPath: '/configuracoes-whatsapp'
      preLoaderRoute: typeof ConfiguracoesWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-pacientes': {
      id: '/configuracoes-pacientes'
      path: '/configuracoes-pacientes'
      fullPath: '/configuracoes-pacientes'
      preLoaderRoute: typeof ConfiguracoesPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-medicos': {
      id: '/configuracoes-medicos'
      path: '/configuracoes-medicos'
      fullPath: '/configuracoes-medicos'
      preLoaderRoute: typeof ConfiguracoesMedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-dados-clinica': {
      id: '/configuracoes-dados-clinica'
      path: '/configuracoes-dados-clinica'
      fullPath: '/configuracoes-dados-clinica'
      preLoaderRoute: typeof ConfiguracoesDadosClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-base-conhecimento': {
      id: '/configuracoes-base-conhecimento'
      path: '/configuracoes-base-conhecimento'
      fullPath: '/configuracoes-base-conhecimento'
      preLoaderRoute: typeof ConfiguracoesBaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-agenda': {
      id: '/configuracoes-agenda'
      path: '/configuracoes-agenda'
      fullPath: '/configuracoes-agenda'
      preLoaderRoute: typeof ConfiguracoesAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AtendimentoRoute: AtendimentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConfiguracoesAgendaRoute: ConfiguracoesAgendaRoute,
  ConfiguracoesBaseConhecimentoRoute: ConfiguracoesBaseConhecimentoRoute,
  ConfiguracoesDadosClinicaRoute: ConfiguracoesDadosClinicaRoute,
  ConfiguracoesMedicosRoute: ConfiguracoesMedicosRoute,
  ConfiguracoesPacientesRoute: ConfiguracoesPacientesRoute,
  ConfiguracoesWhatsappRoute: ConfiguracoesWhatsappRoute,
  LoginRoute: LoginRoute,
  PortalMedicoRoute: PortalMedicoRoute,
  RedesSociaisRoute: RedesSociaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
